# Generated by Django 3.1.7 on 2021-04-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artileupdown',
            name='ups',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='artileupdown',
            name='is_up',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='是否点赞'),
        ),
    ]
