# Generated by Django 3.1.7 on 2021-04-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210416_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='down_count',
            field=models.PositiveIntegerField(default=0, verbose_name='反对数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
