# Generated by Django 3.1.7 on 2021-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210416_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artileupdown',
            name='is_up',
            field=models.BooleanField(default=False, verbose_name='是否点赞'),
        ),
    ]
