# Generated by Django 3.1.7 on 2021-04-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210416_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artileupdown',
            name='is_up',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='是否点赞'),
        ),
    ]
