# Generated by Django 3.1.7 on 2021-04-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210407_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active',
            field=models.BooleanField(default=True, verbose_name='邮箱激活状态'),
        ),
    ]
