# Generated by Django 3.1.7 on 2021-04-12 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_openid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='openid',
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=64, verbose_name='openid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Github登录用户数据',
                'verbose_name_plural': 'Github登录用户数据',
                'db_table': 'tb_oauth_github',
            },
        ),
    ]
