# Generated by Django 3.1.7 on 2021-04-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210412_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='blogger',
            field=models.BooleanField(default=False),
        ),
    ]
